notifications:
  slack: 601-h17-eq2:pdSywKBC71uiHz8xYNbNXBEA
language: android
sudo: required
jdk: oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
android:
  components:
  - tools
  - platform-tools
  - android-25
  - build-tools-25.0.2
  - extra-android-m2repository
before_script:
- chmod +x gradlew
script:
- "./gradlew build"
- "./gradlew assembleRelease"
after_success:
- sh set_tags.sh
deploy:
  provider: releases
  api_key:
    secure: xxXRmZ5+yRavfK0e7RiKdUWxBOQKPNiFR1SaBDI19gnziA+6yevffHdAi32SWrEqwH8XXAJZpEvhgDXmi3SFPrwHKzeOWaWo8TnIKv12AFNSrZlpzUYg+Wi1fXk5gRsa9ctK76W+BLm3Y80i0zZUagGHO+HWE9cNSh0fs37/donyZJc48XmwBovtHaXVRHsLVnokZg3P03JVJzsG85jFYBnCHLzlrammKoQghp39I6cfXHN4tpTyln1dF6YqR7FUXLOqU3X15UjsAFd8CLA5Ou23fg1MEqzM8LQ53fHM5YWZ93Qp6H4tEZK/ynqprt0yhqsSKak7cBxzjYnNBEB21thw+vhwct2EqouUk+jBp4Q5S0JfsvvbclES+KLRSx2LzhOwY0UWCHmMQVdqutEkFgdc8z3tp/A4i4PAxBWc7OpBBHMjL5XjDN+9vhiL+DXguqEwoJJJ3/+3CTTMvN3LGTNDOhaID2QaNIf7xfXV4ZJID/WFIJRivtOFeauCD+hlg3YkTohTcT1Wk0qfHCRh0GvI1iRtaTsquchGNANpiGXb/ehd1crbLq7C4aGrHUz4gzNNbq1dUSN3h7sghiIG4UQZ5C9eNA2gDEqGbQtWggFzUeWZBtmg6KkotLzbzzI8T9rDzfAfmrWQLCTyZIX12e6aB62t/eNBkmZZiGKPvgc=
  file: app/build/outputs/apk/app-release.apk
  file_glob: 'true'
  skip_cleanup: true
  on:
    repo: 601-H17/GeoApp
env:
  global:
    secure: wvo0+jNM9GtmqZZ4cbiIETiHFp8VBwm2MU9cfQSMC438aM105/VPzik7ey1AMHF8tA5VFor5zQIFXAm9/kGkWm0W7kp5qiEAXLBPBdfM+QnRbyRW3FBqtwZYHENm2f9TibBU2X6H+SWg7rN0n6yiWyeZ7UMjfeoKvWumztIhpWPhKn5wqaPoJzWKbrGQPDo24A27Oo8H9f75jD8A+IGEQN+kkm9KMOcVia9zrvht8EGMZDjkLOTpRBgnIdygVj9i6g9e+tUeBJiw6VxE1b8KG5qC1cCDfGdRuXl0I4fzmJMwijRRzPH16A7JjB2rd+Egdt8z1bBaeirOxhC/KDVQm5PZLEae1yrP5+vraslBTI55SwFJ9FK6svjULOVOXTR8s5MFw/Y4arP/kE+7H5Bd83DM8NzngC3LxJj4qvge+VugPwrvbBCOSKrr4UTB5LbzSfsKIuxZN6Z06fK7H3X/H5yUfPyH4ejd7kDAGHaataG8ruq0ALDfeC3QF+lJLnumD9DS/9VynyLd5IL+/O68JBtgTK+v68Ng0v/fa10i3NThBnDFrZY5CehF6yjsTor4kSEkb9QoE0xm108Ls8/m6RafLhgtjQgsFHIUnWZmMbDx9Em4DQabdyeZWF6TZ6gDEpXMLC7iyOab0PNEyc4fzcBIqRrmMjEHPY3uOyHaZgo=
