---
checked_completion: true
completion_version: 1.8.6
last_check:
  etag: '"c8cec9488e32c598e353255976c55c22"'
  version: 1.8.6
  at: 1486495945
endpoints:
  https://api.travis-ci.org/:
    access_token: 
repos:
  601-H17/GeoApp:
    endpoint: https://api.travis-ci.org/
